### ISSUE TITLE
why is h2 showing a #

### ISSUE THREAD

**Issue by dapeng09** [probberechts/hexo-theme-cactus#101]
I can see that in Hello-World page, is that on purpose?

**Comment by probberechts** [comment]
Yes, it is on purpose. I like how it visually highlights the separation between different sections in your text. If you don't like it, you can easily disable it by removing [this line](https://github.com/probberechts/hexo-theme-cactus/blob/79ec248679cd7cff41805d73d58937ed5d40f21d/source/css/_partial/article.styl#L32)

**Comment by dapeng09** [comment]
thanks Bro
