### ISSUE TITLE
how to setting Tags/categories/search page

### ISSUE THREAD

**Issue by lapDog** [probberechts/hexo-theme-cactus#103]
When I set it up as a document, it was an empty page body. i dont know how to setting it.Can you supplement the detailed documentation. thks.

**Comment by probberechts** [comment]
You can add a search box to any page by adding `search: true` to the front-matter. For example,

```
$ hexo new page search
$ cat <<EOT > source/search/index.md
title: search
search: true
---
EOT
```

I haven't implemented a layout for a tags and categories page yet. See my answer in #35 for a solution.
