### ISSUE TITLE
A question about code's grammer of markdown

### ISSUE THREAD

**Issue by pwxcoo** [probberechts/hexo-theme-cactus#104]
Maybe it has no connection about this project itself.

I found a exciting thing that the code's part has a string above code about file's name while I was browsing the [demo](https://probberechts.github.io/hexo-theme-cactus/cactus-dark/public/2016/11/14/hello-world/).

I mean it is that:
![filename](https://i.loli.net/2018/06/05/5b15ec1f2ca39.png)

how I can add filename like it when I write markdown.

I searched no correct results with Google so that I open a issue to seek for the answer...

**Comment by probberechts** [comment]
Here is the source:

```
{% codeblock "Hello world" lang:python http://github.com/ hello_world.py %}
print "Hello World!"
=> "Hello World!"
{% endcodeblock %}
```
