### ISSUE TITLE
dark themed code highlights

### ISSUE THREAD

**Issue by ft9292** [probberechts/hexo-theme-cactus#107]
Hello, 

I've ran through most of the code highlight templates, however they're all light themed. Any way to configure dark theme code highlighting? 
Thanks

**Comment by probberechts** [comment]
The background of the code block is determined by the color theme. To change the background color you should overwrite the `$color-background-code` variable in one of the themes in `source/css/_colors/`. 

See issue #67 for more information.

**Comment by ft9292** [comment]
Thank you
