### ISSUE TITLE
How can I configure different fonts？

### ISSUE THREAD

**Issue by guangxuan126** [probberechts/hexo-theme-cactus#111]
In `_fonts.styl` :
```
@font-face
  font-style: normal
  font-family: "Meslo LG"
  src: local("Meslo LG S"), url("../lib/meslo-LG/MesloLGS-Regular.ttf") format("truetype")

```

there only have one font-family, I want to add  more font-family ,what should I do?
such as in English, it will be used `Meslo LG`, in Chinese, it will be used another font.

thanks.

**Comment by probberechts** [comment]
Take a look at the implementation of [rtl (right to left) support](https://github.com/probberechts/hexo-theme-cactus/blob/master/source/css/rtl.styl). You can use the same approach.

**Comment by guangxuan126** [comment]
thanks.

**Comment by Li-Mingshuang** [comment]
> Take a look at the implementation of [rtl (right to left) support](https://github.com/probberechts/hexo-theme-cactus/blob/master/source/css/rtl.styl). You can use the same approach.看一下 rtl（从右到左）支持的实现。您可以使用相同的方法。

It's hard to understand for one without basic.
