### ISSUE TITLE
Changing the layout of the homepage

### ISSUE THREAD

**Issue by Amolith** [probberechts/hexo-theme-cactus#114]
I'm very new to all this so I'm sorry if this is a stupid question.

I would like to change `Writing` to `Posts` and switch the recent posts section with the topics section. I've looked in a few places and tried editing `index.html` directly but that was regenerated (as I expected) and I can't figure out where else the order and titles would be defined. I've edited `themes/cactus/layout/index.ejs` and moved lines 32-36 in between lines 54 and 55 but that just threw an error.

Any help would be *greatly* appreciated!

**Comment by probberechts** [comment]
- To change 'Writing' to 'Posts', you will have to edit the language file corresponding to the language you are using in `languages/`
- To switch the 'Recent posts' with the 'Topics' section, replace `layout/index.ejs:30-55` with
```ejs
<section id="writing">
  <span class="h1"><a href="<%- url_for("archives") %>"><%= __('index.articles') %></a></span>
  <% if (theme.tags_overview && site.tags.length) { %>
  <span class="h2"><%= __('index.most_recent') %></span>
  <% } %>
  <ul class="post-list">
    <% if (theme.posts_overview.show_all_posts) { %>
      <% var show_posts = page.posts.sort('date', 'desc') %>
    <% } else { %>
      <% var show_posts = site.posts.sort('date', 'desc').limit(theme.posts_overview.post_count || 5) %>
    <% } %>
    <% show_posts.each(function(post, i){ %>
      <li class="post-item">
        <%- partial('_partial/post/date', { post: post, class_name: 'meta' }) %>
        <span><%- partial('_partial/post/title', { post: post, index: true, class_name: '' }) %></span>
      </li>
    <% }); %>
  </ul>
  <% if (theme.posts_overview.show_all_posts) { %>
    <%- partial('_partial/pagination') %>
  <% } %>
  <% if (theme.tags_overview && site.tags.length) { %>
  <span class="h2"><%= __('index.topics') %></span>
  <span class="widget tagcloud">
    <%- tagcloud(theme.tags_overview) %>
  </span>
  <% } %>
</section>
```

**Comment by Amolith** [comment]
That is exactly what I was wanting! Thank you so much! I haven't changed any of the colours yet and that's next on my todo list but here's the website if you're interested! 

https://nixnet.xyz

It's currently hosted on my Raspberry Pi sitting in my living room.
