### ISSUE TITLE
Error / question: TOC sidebar for blog exludes level 1 headings

### ISSUE THREAD

**Issue by RichardJECooke** [probberechts/hexo-theme-cactus#118]
The sidebar in a blogpost only shows level 2 headings and lower. So this:
```
# Chapter 1
## Introduction
It was a dark and stormy night
# Chapter 2
```
wont' show chapter 1 or 2.  How do I show them please?  I can't find anything in your theme files other than `<%- toc(page.content) %>`

**Comment by RichardJECooke** [comment]
Never mind, found it in actions_desktop.styl and actions_mobile.styl and changed to:

```
    .toc-level-1 > .toc-link
      // display: none
      font-weight: bold
      font-size: .8rem

      &:before
        color: $color-accent-1
        content: "#"

    .toc-level-2
      color: $color-text
      font-size: .8rem

      &:before
        color: $color-accent-1
        content: "-"
```

**Comment by probberechts** [comment]
You should note that `# Chapter 1` gets converted to `<h1>Chapter 1</h1>`.  The only `h1` in a blog post should be the blog post title, so you probably don't want any level one headings in your blog post markdown.
