### ISSUE TITLE
when i hexo new archive xxx ,A BUG COMES

### ISSUE THREAD

**Issue by kenthigh** [probberechts/hexo-theme-cactus#120]
![image](https://user-images.githubusercontent.com/8178317/45755025-cea29580-bc4f-11e8-8df7-5ccc7228366b.png)

**Comment by probberechts** [comment]
The `hexo new` command creates a new post or a new page. You created a post with the layout of an archive. That is simply not a valid operation. You have three options:
1. `hexo new page xxx`
2. `hexo new post xxx`
3. `hexo new draft xxx`

See the [Hexo documentation](https://hexo.io/docs/writing.html) for more details.
