### ISSUE TITLE
[help] console error

### ISSUE THREAD

**Issue by ngxlua** [probberechts/hexo-theme-cactus#124]
like this:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/31426367/46594230-44d64180-cb04-11e8-90da-99f73114047d.png">

**Comment by probberechts** [comment]
Could you check the following first:
1.  check whether the error persists when you disable all your browser plugins
2. do you get the same error on [the demo](https://probberechts.github.io/hexo-theme-cactus/cactus-dark/public/)?

**Comment by ngxlua** [comment]
Thanks, it is caused by my browser plugin.
