### ISSUE TITLE
can't  use  the "search " function "

### ISSUE THREAD

**Issue by yokee99** [probberechts/hexo-theme-cactus#127]
I had  installed  search plugin ,  and created the search page , and add the "search : true " into the post markdown file   ,and link the navigation menu . but  I can't   use the search function .    where  is  my mistake ?

**Comment by probberechts** [comment]
What do you mean by "I can't use the search function"? Doesn't the "Search" page exist, isn't there an input box, don't you get any results, do you get an error, ...?

**Comment by yokee99** [comment]
Sorry. I did not express clearly。 In my Website ， The search Page was exists ，but the it is blank, and isn't there a box of input the search keywords.

**Comment by probberechts** [comment]
If the search input box isn't displayed, there is probably something wrong in your `source/search/index.md` file. Could you verify whether this file has the following content:
```
---
title: search
search: true
---
```

**Comment by yokee99** [comment]
Really thank for  your help  .      I had added the '**search: true** ' into the all markdown file in ```source/_post/```   ,    not check the ```search/index.md```  ,it is my mistake.     The problem was solved now .  I like your theme ,thank you .
