### ISSUE TITLE
How to update hexo-theme-cactus?

### ISSUE THREAD

**Issue by MurasakiSeiFu** [probberechts/hexo-theme-cactus#129]
Now I find that this theme has been updated a lot, I am very happy, and I also have a question, do I need to update the theme in my local?
I am a Java development engineer. Hey, this is my blog: http://ilovenorth.life/ Forgive me for not knowing about page design. I really hope that this theme can have a photo album module, because my life is inseparable from my blog.
thank you very much!

**Comment by probberechts** [comment]
If you installed it as proposed in the README, the following should work:
```git
$ cd themes/cactus
$ git pull origin master
```
If you made some adaptations to the team, you might have to fix some merge conflicts.
