### ISSUE TITLE
Is It Possible to Overwrite Cactus's _config.yml Settings in My Own Project Root

### ISSUE THREAD

**Issue by oldcai** [probberechts/hexo-theme-cactus#130]
Configs the `_config.yml` in my own project does not work,
 it works only if I change the settings in `themes/cactus/_config.yml`

Is there a namespace or something Cactus Has a Namespace or Something in `_config.yml` to prevent settings being overwriten?

It would be safer if settings could be write in my own project instead of in the theme directory for further upgrade.

**Comment by probberechts** [comment]
Quoting the README:

> There are two possible methods to override the defaults. As a first option, you could fork the theme and maintain a custom branch with your settings. Alternatively, you can configure it from your site's primary configuration file. Therefore, **define your custom settings under the `theme_config` variable**. For example:
```yaml
# _config.yml
theme_config:
  colorscheme: white
```
