### ISSUE TITLE
Search results don't show up

### ISSUE THREAD

**Issue by Ryziii** [probberechts/hexo-theme-cactus#134]
按照load search操作后部署服务器上发现search页面输入查找关键字后显示不出查找结果

**Comment by probberechts** [comment]
Can you translate this? I can't figure out what you mean with Google Translate.

**Comment by probberechts** [comment]
Could you try to verify these things:
- Are there any errors in the Javascript console?
- Is the `search.xml` file generated?
- Does it work on <https://probberechts.github.io/hexo-theme-cactus/cactus-dark/public/search/>?
- Try to disable all your browser plugins

**Comment by probberechts** [comment]
Does it work if you replace [L21 in layout/_partial/scripts](https://github.com/probberechts/hexo-theme-cactus/blob/e544c2d2345517add0d31bcac006e7c8309e6f78/layout/_partial/scripts.ejs#L21) with the line below?
```
inputArea.onkeydown = function(event){
```
Oddly enough, I don't get that error in my browser.

**Comment by Ryziii** [comment]
> Does it work if you replace [L21 in layout/_partial/scripts](https://github.com/probberechts/hexo-theme-cactus/blob/e544c2d2345517add0d31bcac006e7c8309e6f78/layout/_partial/scripts.ejs#L21) with the line below?
> 
> ```
> inputArea.onkeydown = function(event){
> ```
> Oddly enough, I don't get that error in my browser.

it also doesn't work
qaq

**Comment by probberechts** [comment]
Second attempt. What if you do this:
```js
inputArea.onkeydown = function(event){
    if (event===undefined) event = window.event;
    if (event.keyCode==13) {
         return false
    }
}
````

I'm sorry, but I can't debug it myself since I don't get the error.

**Comment by Ryziii** [comment]
> Second attempt. What if you do this:
> 
> ```js
> inputArea.onkeydown = function(event){
>     if (event===undefined) event = window.event;
>     if (event.keyCode==13) {
>          return false
>     }
> }
> ```
> 
> I'm sorry, but I can't debug it myself since I don't get the error.

it is also doesn't work, maybe this message will be help for you to diagnose my error
![image](https://user-images.githubusercontent.com/20976649/47557885-6cbb0700-d944-11e8-8566-213c815b92c3.png)
one click appear one error message

**Comment by probberechts** [comment]
But the console error is gone, right? If so, it is probably a problem with your local configuration. What did you put in `_config.yml` and what is the contents of `public/search.xml`?

**Comment by Ryziii** [comment]
> But the console error is gone, right? If so, it is probably a problem with your local configuration. What did you put in `_config.yml` and what is the contents of `public/search.xml`?

the console error also appear, i have the `public/search.json` no file `public/search.xml`

**Comment by Ryziii** [comment]
`# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ryziii Blog
subtitle: 层楼纵终究误少年，自由早晚乱余生
description:
keywords:
author: Ryziii
language: zh
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://coeji.xyz
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Site settings
# 网站综合内容设置：
SEOTitle: Ryziii的博客 | Ryziii's Blog
# header-img: img/home-bg.jpg
# email: onlythen@yeah.net
# description: "聂小涛的博客"
# keyword: "腾讯"
  
#SNS
weibo_username: xx
github_username: ryziii


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-cactus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@x.x.x.x:/var/repo/hexo_static.git
  branch: master

sidebar-avatar: img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

search:
  path: search.json
  field: post

encrypt: 
  password: x

backup:
    type: git
    repository:
       github: git@github.com:Ryziii/hexo.git,master`

**Comment by probberechts** [comment]
The console error should be gone. Make sure to update the theme and run `hexo clean`.

The search doesn't work because json is not supported, you should generate an xml file. Put the following in your `_config.yml` file:

```yml
search:
  path: search.xml
  field: post
  content: true
```

**Comment by Ryziii** [comment]
> The console error should be gone. Make sure to update the theme and run `hexo clean`.
> 
> The search doesn't work because json is not supported, you should generate an xml file. Put the following in your `_config.yml` file:
> 
> ```yaml
> search:
>   path: search.xml
>   field: post
>   content: true
> ```

OMG! The problem was solved, I'll Modify  as you say and still can't work, then I see the console have some error,  I found the keyword `cdata` in my post article and add ``  in that line, final it is work!!

**Comment by Ryziii** [comment]
can you add the "update time" feature ?
when the post article head add "update time" then in home page can see the newest article.

**Comment by probberechts** [comment]
> can you add the "update time" feature ?
> when the post article head add "update time" then in home page can see the newest article.

Create a separate issue for this.
