### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by rpartha** [probberechts/hexo-theme-cactus#135]
Does local search only work on deployed websites? I would like to know if there is a way to test on localhost (i.e. via hexo generate && hexo server). I don't see a search.xml generated either though I set 
`search: true` in the markdown files (including search > index.md)

**Comment by loveminimal** [comment]
> Does local search only work on deployed websites? I would like to know if there is a way to test on localhost (i.e. via hexo generate && hexo server). I don't see a search.xml generated either though I set
> `search: true` in the markdown files (including search > index.md)

![answer](https://user-images.githubusercontent.com/23427211/47612074-ff2aea00-daad-11e8-8b20-276b7106d7bb.png)

Here's a introduction. Please read the README file.   : )

**Comment by JustYummy** [comment]
It works for both website and localhost, you should follow the instruction [here](
https://github.com/probberechts/hexo-theme-cactus#local-search)!
Also you need to add some code in `_config.yml`, the one you configured for your website, not the theme configuration.
```stylus
search:
  path: search.xml
  field: post
  content: true
```

**Comment by rpartha** [comment]
thank you. I don't know how I missed that. I'll update tonight.
