### ISSUE TITLE
TOC on pages

### ISSUE THREAD

**Issue by janvaniperen** [probberechts/hexo-theme-cactus#142]
How can I enforce TOC on *pages*? It works perfectly and automagically on posts, but cannot call it into pages.
With or without h1 it does not show and adding `toc: true` to the front matter does not have any impact.

**Comment by probberechts** [comment]
I did not implement a TOC for normal pages and don't plan to do so. If you want one, you have to implement it yourself. Therefore, you should add this line 
```
<div id='toc'><%- toc(page.content) %></div>
```
somewhere in `layout/page.ejs` and add the necessary css to `source/css/_partial/article.styl`.

**Comment by janvaniperen** [comment]
Thanks, appreciate the pointer in the right direction.
