### ISSUE TITLE
Tables overflow without scrollbar

### ISSUE THREAD

**Issue by AGIsmail** [probberechts/hexo-theme-cactus#144]
**Issue**: If you have a very long table, the table overflows the width of the page. No scrollbar appears as is the case with code blocks.

**Screenshot**: 
![screenshot_20190111_160801](https://user-images.githubusercontent.com/11680600/51059805-7525f400-15bb-11e9-83dc-6f54578e2d33.png)

**Fix**: edit table CSS in _extend.styl to include `overflow: auto` and `display: block`

**Proof of fix**:
![screenshot_20190111_161032](https://user-images.githubusercontent.com/11680600/51059814-7e16c580-15bb-11e9-8269-2ce50f428afd.png)

I'll issue a PR in a minute.

**Comment by probberechts** [comment]
Thanks!
