### ISSUE TITLE
about search

### ISSUE THREAD

**Issue by sniu0320** [probberechts/hexo-theme-cactus#146]
why?
http://localhost:4000/search/undefined/   
how to 
http://localhost:4000/post/XXXX

**Comment by sniu0320** [comment]
The URL address of the search results is incorrect. How to deal with it? I don't know what's affecting the configuration here.

**Comment by probberechts** [comment]
I suspect that you did something wrong while running the command 
```
$ hexo new page search
```

What do you get when you run `tree source` in the root of your site? You should get something like this: 
```
source
├── _posts
│   └── hello_world.md
├── categories
│   └── index.md
├── page
│   └── index.md
├── search
│   └── index.md
└── tags
    └── index.md
```

**Comment by sniu0320** [comment]
~/hexo_blog/source  tree
.
├── CNAME
├── _posts
│   ├── 2018年�\210�\200��\223.md
│   ├── CentOS7�\203�署GateOne.md
│   ├── CentOS7�\203�署Nginx.md
│   ├── linux�\224记.md
│   ├── python-script-�\204�\220\206�\227��\227�\226\207件.md
│   ├── python3�\211�\205.md
│   ├── python�\217�\213�\217.md
│   ├── �\200\220转载�\200\221�\217\220�\215\207产�\223\201质�\207\217-�\234\200�\202质�\207\217.md
│   ├── �\201\232�\200�\220\215�\230�\200�\232\204软件�\213�\225工�\213�\210.md
│   ├── �\212�BUG�\230��\200�\227�学�\227�.md
│   └── 转载-�\234\237正�\216\211害�\232\204人�\214�\227�已�\210\222�\216\211�\206�\203\205绪.md
├── about
│   └── index.md
├── categories
│   └── index.md
├── search
│   └── index.md
└── tags
    └── index.md

**Comment by probberechts** [comment]
That seems ok. What is the exact URL for these posts in the search results? For example for the `linux�\224记.md` post? Also, could you post your `_config.yml` file?

**Comment by sniu0320** [comment]
<img width="1280" alt="2019-01-27 11 51 32" src="https://user-images.githubusercontent.com/43646374/51803322-bfcb8f80-228e-11e9-9532-638e207f7e6e.png">
By searching, I got the wrong address for the article, as shown in the figure.
It should be this：http://localhost:4000/posts/fa88ee57.html

**Comment by probberechts** [comment]
Ok. I get that, but I will need more information to pinpoint the cause of the problem. Could you please post your `_config.yml` file and a part of the `public/search.xml` file?

**Comment by sniu0320** [comment]
[log.zip](https://github.com/probberechts/hexo-theme-cactus/files/2824383/log.zip)

**Comment by probberechts** [comment]
Thansk. I've found the problem. You installed the wrong plugin to generate the search index file. This theme only supports [hexo-generator-search](https://github.com/wzpan/hexo-generator-search), while you installed [hexo-generator-searchdb](https://github.com/theme-next/hexo-generator-searchdb).

**Comment by sniu0320** [comment]
谢谢，搞定了
Thank you. It's done.
