### ISSUE TITLE
Post info

### ISSUE THREAD

**Issue by h0ek** [probberechts/hexo-theme-cactus#150]
I am still using older version of theme and post page under the topic of post go info in one line:

POST TITLE
PAGE NAME date | category_name | #tag1, #tag2, #tag3

I updated to the latest one in my test environment and it looks like:

POST TITLE
PAGE NAME 2018-07-30
 category
 | #tag1, #tag2, #tag3

it's only me or you also got same issue?

**Comment by h0ek** [comment]
article.style is missing some lines for category display:

```
.article-category
  .category-link

    underline(10px, $color-link)
```
this entry in article.style is making category link looks good but still categories and tags are in separate lines, not in same line with date.

**Comment by h0ek** [comment]
If you add these lines at the end of article.style file, everything looks good then.

```
.article-category
  .category-link

    underline(10px, $color-link)
      
@media (min-width: 480px)
  .article-category
    display: inline

    &:before
      content: "|"
```

**Comment by probberechts** [comment]
Thanks for your help!

**Comment by h0ek** [comment]
@probberechts 
Hmm one more thing. Looks like after this update tag word is not a link anymore. You can't click it in the same way like category.

**Comment by probberechts** [comment]
Strange. I don't encounter any issues. Could you post both the markdown source and generated html of the post that causes problems?

**Comment by h0ek** [comment]
Right. Sorry. It was my browser cache.
