### ISSUE TITLE
about share button

### ISSUE THREAD

**Issue by jluncc** [probberechts/hexo-theme-cactus#154]
Hi~
If there a setting to hide the share button ?
Or how can I hide the share button, because I think I would not use this button.
Thanks~

**Comment by probberechts** [comment]
You can just remove the links that open the share menu from [layout/_partial/post/actions_mobile.ejs](https://github.com/probberechts/hexo-theme-cactus/blob/e39a9bea5629ec4d65e2a85b77f134b9655ac4a9/layout/_partial/post/actions_mobile.ejs#L23) and [layout/_partial/post/actions_desktop.ejs](https://github.com/probberechts/hexo-theme-cactus/blob/e39a9bea5629ec4d65e2a85b77f134b9655ac4a9/layout/_partial/post/actions_desktop.ejs#L28).

**Comment by jluncc** [comment]
got it, thanks~
that is what i want to know
