### ISSUE TITLE
Article page click share button is greater than 10 times menu bar layout change

### ISSUE THREAD

**Issue by change1st** [probberechts/hexo-theme-cactus#158]
I modified the menu attribute margin-right: 0rem in actions_desktop.styl to work normally.
`  #menu
    visibility: hidden
    margin-right: 0rem`

**Comment by probberechts** [comment]
1. I don't get the title of this issue. Grammatically, it does not make any sense. Could you please try to explain the problem better? Maybe post a screenshot.
2. I tried to make the change that you suggested, but that breaks the layout. The navigation links move to the next line. This is what happens:
<img width="411" alt="screenshot 2019-03-07 at 17 29 05" src="https://user-images.githubusercontent.com/2175271/53972247-b55aac00-40fe-11e9-9d83-3d212b62876e.png">
