### ISSUE TITLE
Feature to allow icon on blog posts

### ISSUE THREAD

**Issue by lanceofwhichwedream** [probberechts/hexo-theme-cactus#169]
I'm a huge fan of the cactus theme, but I'd love to have a configuration option to allow an icon to be displayed on blog posts. I wouldn't be able to help with the coding of the feature, but I'd be more than willing to assist with the documentation of the theme

**Comment by probberechts** [comment]
You will have to be more specific. Would you like to display an icon in the title of the blog post, somewhere in the text, or on the archive page? Do you have an example somewhere?
