### ISSUE TITLE
Jekyll Github Pages Theme

### ISSUE THREAD

**Issue by gebeto** [probberechts/hexo-theme-cactus#170]
Hey! What about rewrite this theme to Jekyll to use it with GitHub Pages?
I can do it, may I?

**Comment by probberechts** [comment]
Sure. Go ahead!

The [license](https://github.com/probberechts/hexo-theme-cactus/blob/master/LICENSE) is very open: you can do whatever you want with this theme, as long as you keep the copyright notice.
