### ISSUE TITLE
Disqus background is white and the font color is white too.

### ISSUE THREAD

**Issue by whitelok** [probberechts/hexo-theme-cactus#173]
Disqus background is white and the font color is white too.
http://whitelok.github.io/2018/09/05/how_to_do_caffemodel_inference_with_tensorrt_with_FP16/

**Comment by probberechts** [comment]
It works on the demo: https://probberechts.github.io/hexo-theme-cactus/cactus-white/public/2016/11/14/hello-world/

Did you check this page: https://help.disqus.com/installation/disqus-appearance-tweaks?
