### ISSUE TITLE
Disqus is not working

### ISSUE THREAD

**Issue by gokomer** [probberechts/hexo-theme-cactus#177]
Below configuration is not working. 

```
disqus:
  enabled: true
  shortname: sitename
```

This one is working with default theme:

```
disqus_enabled: true
disqus_shortname: sitename
```

Am I missing something?

---

After digging a little deeper I found out that you have to put those line under thme_config if you are using global _config.yml.

```
theme_config:
  enabled: true
  shortname: sitename
```

**Comment by mstuttgart** [comment]
This:

```
disqus_enabled: true
disqus_shortname: sitename
```

work for me. Thanks!
