### ISSUE TITLE
Can i TOP my post in my index writing section?

### ISSUE THREAD

**Issue by imoyao** [probberechts/hexo-theme-cactus#178]
I know we can set sort_updated to true in order to
> sort posts by last modification date instead of creation date.  

in [Blog posts list on home page](https://github.com/probberechts/hexo-theme-cactus#blog-posts-list-on-home-page).
Can I just **Sticky Post**  if it is set to true?
```
title: some example post
date: 2019-06-09 10:17:16
tags: foo
categories: bar
// this section pin the article to top if it is set to true
top: true
```
![Top it](https://user-images.githubusercontent.com/22978431/59154756-451c4780-8aac-11e9-9d78-0b78dfe1313e.png)
I'm not good at English and hope you understand what I mean by my statement.

**Comment by imoyao** [comment]
OK,there.I have find a package to satisfied my requirements.Here is the link for someone who has the same requirement:
[hexo-generator-index-pin-top](https://github.com/netcan/hexo-generator-index-pin-top)
You can do it by yourself!

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo-generator-index/pull/51
