### ISSUE TITLE
underline error in firefox

### ISSUE THREAD

**Issue by siaikin** [probberechts/hexo-theme-cactus#179]
look this:
FireFox:
![image](https://user-images.githubusercontent.com/24749324/59551851-37862680-8fb2-11e9-955b-5ff8625ed81d.png)
Chrome:
![image](https://user-images.githubusercontent.com/24749324/59551879-a2376200-8fb2-11e9-89b0-33334375ea68.png)

**Comment by TieWay59** [comment]
.content a:hover {
    background-image: linear-gradient(transparent, transparent 4px, rgba(86,124,119,0.4) 4px, rgba(86,124,119,0.4));
}
我观察到了作者的下划线是用渐变色来实现的，我做过类似的事情，简单地说就是渐变分界点设得很近就会产生划分线得感觉。但在老版本的火狐中，渐变的支持还不够完善，这算是火狐的一个bug。

我的建议是用box-shadow来实现变色下划线，而且还能支持更多动画。

似乎新版本的火狐已经修复了这个问题？

**Comment by probberechts** [comment]
This is resolved in the newest version of Firefox.
