### ISSUE TITLE
consider changing markdown headers rendering

### ISSUE THREAD

**Issue by joejztang** [probberechts/hexo-theme-cactus#180]
I see this themes doesn't support `#` as header1, and from header2 and so on, they are not consistent. pleading changing the rendering.

**Comment by probberechts** [comment]
Note that `# Chapter 1` gets converted to `<h1>Chapter 1</h1>`. The only h1 in a blog post should be the blog post title, so you probably don't want any level one headings in the blog post markdown.

I am not sure whether I understand what you mean by "from header2 and so on, they are not consistent". To me, it seems logical to use a different style for different header levels.
