### ISSUE TITLE
Navigation bar shows puzzling words

### ISSUE THREAD

**Issue by HuangZhenyang** [probberechts/hexo-theme-cactus#184]
Hi! This theme is so cool!
However, I found that Navigation bar shows puzzling words, it just like:

![TIM截图20190731103245](https://user-images.githubusercontent.com/17945092/62179302-a52dbc80-b37e-11e9-92a7-4605c2871c6f.png)

How can I modify it? Thx!

**Comment by probberechts** [comment]
Do you mean the vertical lines between the navigation links? Just delete [this line](https://github.com/probberechts/hexo-theme-cactus/blob/d3b810a37899c5071914fbd0be2020f43aa337bf/source/css/_partial/header.styl#L57)

**Comment by HuangZhenyang** [comment]
Sry, it's my fault! I didn't make my problem clear. 
I mean these two words"Inici", "Qui som" is so fuzzling. How Can I modify it?

**Comment by probberechts** [comment]
You can modify [the language file](https://github.com/probberechts/hexo-theme-cactus/blob/e39a9bea5629ec4d65e2a85b77f134b9655ac4a9/languages/ca.yml#L2-L3).

**Comment by HuangZhenyang** [comment]
Thx! Now I know the reason why my home page shows these words from `ca.yml`.   

Because language setting in the file `_config.yml` in the root of Hexo folder was `zh-Hans`. I checked the language folder in hexo-theme-cactus, and of cause I didn't find such a yml file named `zh-Hans.yml`, so did Hexo. And I thought that was why Hexo took `ca.yml` as default language yml file!

Thank you very much!
