### ISSUE TITLE
Cannot get Project List to work

### ISSUE THREAD

**Issue by SteveALee** [probberechts/hexo-theme-cactus#191]
The readme states we can create a [projects.json](Provides a large clear current play time display when YouTube videos are playing embedded in a webpage) to show a list of project on the home page but I cannot get this to work

Indeed, a search for projects.json only finds the readme.

Plus the URL in the __config.yml appears to be a place holder

**Comment by SteveALee** [comment]
Ah, I see the project list on the home page now. It's cofunsion though that there is a broken projects URL in the default Navigation

**Comment by i-naeem** [comment]
Hey, how did you fix this one? I am still not able to make it work.

**Comment by i-naeem** [comment]
Nevermind  I got it, 

for any having the same issue that your projects are not appearing index page, make sure to create the "projects" page first. You can do this with the following command:  
```sh
hexo new page projects
```

Once the page is created, follow the official documentation to properly list your projects on the index page.
