### ISSUE TITLE
Any plan to add mathjax engine

### ISSUE THREAD

**Issue by Artwalk** [probberechts/hexo-theme-cactus#192]
Hi, first thanks for sharing, I love your dark mode.

One issue I found here is that when I was trying to migrate the theme from `next` to `cactus`, all the math graphs gone.

For instance, sigmoid gradient formula:

```math
g = sigmoid(z).*(1-sigmoid(z));
```

in `next` it can import `mathjax` by using this way:

```yml
math:
  enable: true
  engine: mathjax
```

So, is there any plan to add mathjax engine?

Thanks

**Comment by probberechts** [comment]
There's already a plugin that does this (see [hexo-math](https://github.com/hexojs/hexo-math)).

**Comment by Artwalk** [comment]
> There's already a plugin that does this (see [hexo-math](https://github.com/hexojs/hexo-math)).

Yeah, I used to use `hexo-math` in theme `next`, but with no luck after switch to cactus.
Not sure where went wrong.

BUT `hexo-filter-mathjax` is working and now the formulas are back 🎉🎉🎉, thanks.
