### ISSUE TITLE
How can I configure index page

### ISSUE THREAD

**Issue by eeqe** [probberechts/hexo-theme-cactus#193]
hi, actually it's not an issue but I couldn't find how can I configure main page in here. Thanks.

**Comment by probberechts** [comment]
I'm afraid to your question is too general. Which part of the main page would you like to configure exactly?

Here is an [example `_config.yml`](https://github.com/probberechts/hexo-theme-cactus/blob/site/demos/cactus-classic/_config.yml) file. Maybe that can help you.

**Comment by eeqe** [comment]
thanks for your response, actually I want to configure home page but I couldn't find. I'm sorry I know this question is so weird.
