### ISSUE TITLE
Additional hash charactor "#" in headers

### ISSUE THREAD

**Issue by xSinGle** [probberechts/hexo-theme-cactus#196]
Each article I edited in markdown format will show extra "#" in every header as the photo I show below. 
![image](https://user-images.githubusercontent.com/32978243/68378817-b8bf9f00-0187-11ea-8299-a7caa67f3e59.png)
I have checked and there seems to be no typo error at all.
![image](https://user-images.githubusercontent.com/32978243/68379102-371c4100-0188-11ea-8fcf-3cec4dffabe0.png)
I really wish to use cactus theme for my blog. Would you please help to fix it? thx a lot.

**Comment by probberechts** [comment]
That is not a bug. The # before each H2 is part of the design. See #101.
