### ISSUE TITLE
[Feature] Can we support flowchart & diagram by mermaid?

### ISSUE THREAD

**Issue by imbadark** [probberechts/hexo-theme-cactus#197]
First of all, thank you very much for your work.

And sincerely hope that the theme can support the markdown rendering of the following charts, (when u write the blogs, the charts are more expressive than words.)

The [mermaid-js](https://github.com/mermaid-js/mermaid) has done the work pretty well, maybe we can use it directly?  

Or anyone who is familiar with the `JS` can PR for it?

**Comment by probberechts** [comment]
In my opinion, things like this should be implemented as a plugin. It can be useful in any theme. Maybe you should move this issue to the main hexojs repo?

**Comment by imbadark** [comment]
Thank you for your reply, u're right.

And I've found a workable solution, the plugin has been finished

refer to [hexo-filter-mermaid-diagrams](https://github.com/webappdevelp/hexo-filter-mermaid-diagrams)

Close the issue now.
