### ISSUE TITLE
delete line number highlight

### ISSUE THREAD

**Issue by STnetwork** [probberechts/hexo-theme-cactus#206]
Hi,

I would like to remove the line number of the codepre "highlight.js" how is it possible please ?

**Comment by S4kur4** [comment]
I also want to know, looking forward to the answer.

**Comment by probberechts** [comment]
If you add

```yml
highlight:
  line_number: false
```
to your main _config.yml file, line numbers are disabled for each code block. I don't know whether it is possible to disable line numbers for individual code blocks. If that is what you need, I suggest that you create an issue in the main Hexo repo.
