### ISSUE TITLE
How can I modify the style of text wrapped with backticks quotes?

### ISSUE THREAD

**Issue by Vancir** [probberechts/hexo-theme-cactus#207]
I am satisfied with the cactus theme but not the text wrapped with backticks quotes. 
And I am not familar with web developments. How can I easily modify the style(I just want to highlight it but not enclose it. )

Thanks for your answer.

**Comment by probberechts** [comment]
You should edit the CSS files. I think removing [this line](https://github.com/probberechts/hexo-theme-cactus/blob/a8a450e1d9fa607511181eea051d063e81dbb73a/source/css/style.styl#L147) will do it.

**Comment by Vancir** [comment]
I modified [this part of the code](https://github.com/probberechts/hexo-theme-cactus/blob/a8a450e1d9fa607511181eea051d063e81dbb73a/source/css/style.styl#L145) to the following:
``` 
code
  font-size: 1.1em;
  // background-color: #f8f8f8;
  font-family: 'Roboto Mono', Monaco, courier, monospace;
  margin: 0 2px;
  padding: 3px 5px;
  color: #44cef6;
  border-radius: 2px;
  white-space: inherit;
```
and it seems like better.
