### ISSUE TITLE
[Feature Request] Support click image to enlarge it

### ISSUE THREAD

**Issue by imbadark** [probberechts/hexo-theme-cactus#212]
For now, the picture size on cactus is fixed, it have the same width with the blog's context.

However, some complex or large picture like [this](https://www.thomas-krenn.com/de/wikiDE/images/7/72/Linux-storage-stack-diagram_v4.10.svg) cannot be displayed clearly. (architecture pics)

So could we support to click the picture to expand it to the full screen like [this-style](http://jacman.wuchong.me/2013/12/26/images/), and it will be really useful for press `←` or `→` to switch the images in `picture-enlarge-mode`

_Or maybe there is any `hexo-plugin` can support it directly?_

Thanks for your efforts again

**Comment by imoyao** [comment]
Hey,maybe here is a plugin can help you [hexo-light-gallery](https://github.com/lzane/hexo-light-gallery)?the README is quite simple,but as the owner said: This plugin is based on lightgallery.js. Once you installed, all posts will add lightgallery feature automatically.

**Comment by imbadark** [comment]
> Hey,maybe here is a plugin can help you [hexo-light-gallery](https://github.com/lzane/hexo-light-gallery)?the README is quite simple,but as the owner said: This plugin is based on lightgallery.js. Once you installed, all posts will add lightgallery feature automatically.

Thanks a lot for ur reply, it did works and meet all the needs.
Putting all the pictures together is exactly what I need, thank u again, it really helps me
