### ISSUE TITLE
how to change markdown Quote'font color?

### ISSUE THREAD

**Issue by sky-gg** [probberechts/hexo-theme-cactus#213]
![image](https://user-images.githubusercontent.com/33249562/72065920-4e0f1900-331a-11ea-864c-cc67c026cc35.png)
I'm going blind

**Comment by imoyao** [comment]
hey,you can rewrite those code
```
// themes/cactus/source/css/_partial/article.styl:63
    blockquote
      margin: 1rem 10px
      padding: .5em 10px
      background: inherit
      background-color: #fff6f7; 
      color: $color-quote            # This line. change color here directly or file like "themes/cactus/source/css/_colors/{THEME TYPE YOU ARE USING}.styl:14 "is better.
      quotes: "\201C" "\201D" "\2018" "\2019"
      border-radius: .4em
      border-left: .3em solid #fe6c6f
      font-weight: bold
      font-family: 'Open Sans',"Helvetica Neue", "Helvetica","Microsoft YaHei", "WenQuanYi Micro Hei",Arial, sans-serif
```

**Comment by sky-gg** [comment]
> hey,you can rewrite those code
> 
> ```
> // themes/cactus/source/css/_partial/article.styl:63
>     blockquote
>       margin: 1rem 10px
>       padding: .5em 10px
>       background: inherit
>       background-color: #fff6f7; 
>       color: $color-quote            # This line. change color here directly or file like "themes/cactus/source/css/_colors/{THEME TYPE YOU ARE USING}.styl:14 "is better.
>       quotes: "\201C" "\201D" "\2018" "\2019"
>       border-radius: .4em
>       border-left: .3em solid #fe6c6f
>       font-weight: bold
>       font-family: 'Open Sans',"Helvetica Neue", "Helvetica","Microsoft YaHei", "WenQuanYi Micro Hei",Arial, sans-serif
> ```

thanks~
