### ISSUE TITLE
[Question] Only new posts support Disqus's emotion feedback?

### ISSUE THREAD

**Issue by imbadark** [probberechts/hexo-theme-cactus#226]
Desc:
[Disqus ](https://disqus.com/) supports a new feature allows people to vote for a article like this:

![temp](https://user-images.githubusercontent.com/38650392/77345424-8cd83b00-6d6f-11ea-9c5d-2226927a8526.jpg)

However, when I open this feature in disqus, I found only new posts could show the feedback area, and old posts(even has been updated) cannot show it.

I also try to use `hexo clean && hexo g -d` to rebuild posts, but it didn't work.

Wonder how to make all posts support disqus's feedback? Is it a theme problem? Or anyone knows the reason

**Comment by probberechts** [comment]
I can enable reactions on old blog post by following the [instructions provided by Disqus](https://help.disqus.com/en/articles/2199501-reactions). Anyhow, this issue is not related to this theme.  If you have problems with this you should reach out to Disqus for support.

**Comment by imbadark** [comment]
Sorry to disturb, when I used the feedback function before, I didn't see the button to allow old articles to be displayed.
Then I simply checked the loading of disqus-js file, but didn't get useful info, so I thought it maybe a problem of the theme itself. I should read the official doc clearly, apologize again, and thank you for your reminding
