### ISSUE TITLE
Toc interferes in proper rendering of the page while printing

### ISSUE THREAD

**Issue by sac0** [probberechts/hexo-theme-cactus#227]
<img width="466" alt="Screenshot 2020-03-24 at 00 40 07" src="https://user-images.githubusercontent.com/20946852/77354149-4b905d00-6d68-11ea-8e9c-528bfa76de33.png">

I have a quick fix for it. I will raise a pull request for it.
@probberechts , This is my first pull request. Please let me know if i have to change something. High anticipating to get this merged.

Thank you for creating such a great theme. I'm using it for my website https://sachingovind.com

**Comment by sac0** [comment]
https://github.com/probberechts/hexo-theme-cactus/pull/228. Please have a look at this and let me know if any other change is needed. Thanks a lot again for the wonderful theme,

**Comment by probberechts** [comment]
Thanks! I merged your PR.
