### ISSUE TITLE
Add a Copyright Notice to Copied Text

### ISSUE THREAD

**Issue by FENG1000** [probberechts/hexo-theme-cactus#232]
主题中是否能添加一个设置版权声明的功能

**Comment by FENG1000** [comment]
就是在每篇博客底部都生成一个包含有当前链接的版权声明，在复制博客内容时，在末尾也会自动添加上

**Comment by probberechts** [comment]
I do not plan to implement that. It will annoy most users and people who do not like it will remove it anyway after they paste the text. That being said, it is very easy to add this yourself. You can simply add [this script](https://bavotasan.com/2010/add-a-copyright-notice-to-copied-text/) to the theme's javascript.
