### ISSUE TITLE
Hello i have some questions

### ISSUE THREAD

**Issue by lnzu** [probberechts/hexo-theme-cactus#233]
Hello, I like your theme very much. Now it has been used on my blog. thank you.

After I open the demo of this topic, I will open the article Hello world
![9463E5F5-0D7D-4CE9-ACD7-958CE6F310BC](https://user-images.githubusercontent.com/43702266/80699834-41a00d80-8b0f-11ea-911d-42574631b1c7.jpeg)
I want to know how to write markdown file and get "Hello world" and "Hello world. Py" as shown above.

Thank you, hope to get your reply!

**Comment by utkarshbhatt12** [comment]
It's mentioned in the examples in [plugin](https://hexo.io/docs/tag-plugins#Code-Block)

```{% codeblock Hello World lang:py https://example.com/static/hello.py hello_world.py %}
print "Hello World"
=> "Hello World"
{% endcodeblock %}```

**Comment by lnzu** [comment]
ha ha ,Thank you very much!
