### ISSUE TITLE
How to make About as Home, Home as Blog

### ISSUE THREAD

**Issue by Reapor-Yurnero** [probberechts/hexo-theme-cactus#236]
Hi folks I'm new to hexo and cactus. I'm planning to use cactus as a personal webpage. I like this kind of simple style. However, what I want is a little bit different from the default. I hope the homepage of my website, should be something like the 'about' page right now where I put some self-introduction. I played around the config file for a while but didn't work it out completely. Does anyone have any idea? 

By the way, is there any nice plugin for this theme or hexo to put cv/resume electronically?

Thank you so much!

**Comment by probberechts** [comment]
To change the layout of the home page, you will have to edit the `layout/index.ejs` file. If you want something like the about page, you can copy the layout from `layout/page.ejs`.

I am not aware of any plugins for a cv. You can upload it as a PDF file or create your own custom layout file in `layout/cs.ejs`.
