### ISSUE TITLE
Inline code occupies a whole line sometimes

### ISSUE THREAD

**Issue by fiigii** [probberechts/hexo-theme-cactus#239]
Today I updated the theme via `git pull`. But some inline elements' style gets broken, which includes inline code, links, emphasized works, etc. For example:
<img width="762" alt="Screen Shot 2020-07-19 at 12 28 55 AM" src="https://user-images.githubusercontent.com/1263030/87869950-bf2e2980-c958-11ea-8283-486c52e91424.png">

This problem seems from https://github.com/probberechts/hexo-theme-cactus/blob/e8936294b7d09234ecb61bbdcd337b59e67fd3f0/source/css/style.styl#L40

**Comment by probberechts** [comment]
Can you post the markdown source of this example?

**Comment by metters** [comment]
I think this issue can be closed.
At least it does not occur anymore on [fiigii's website](https://fiigii.com/2020/02/16/Does-register-selection-matter-to-performance-on-x86-CPUs/#Partial-Register-Stall):
<img width="927" alt="Screenshot 2023-01-04 at 12 59 24" src="https://user-images.githubusercontent.com/9088722/210550546-20b54d27-9d87-4fb4-9ff9-4aa2540c69c7.png">
