### ISSUE TITLE
Change copyright to CC-BY

### ISSUE THREAD

**Issue by larkinrt** [probberechts/hexo-theme-cactus#241]
Hi, I was wondering if there is a simple way to go about changing the copyright notice at the bottom of the page to CC-BY.
Thanks!

**Comment by probberechts** [comment]
You can create a custom language file and overwrite the `copyright` tag or clone the theme and change [the corresponding line](https://github.com/probberechts/hexo-theme-cactus/blob/e8936294b7d09234ecb61bbdcd337b59e67fd3f0/layout/_partial/footer.ejs#L3).
