### ISSUE TITLE
Support for using hash on gravatar options directly

### ISSUE THREAD

**Issue by CSY54** [probberechts/hexo-theme-cactus#243]
While configuring the theme, I noticed these comments.
```
# Fill in you Gravatar user id / email if you want to use your gravatar as the
# logo and/or favicons of you website.
gravatar:
  email: name@email.com
```
It says you can fill in the user id or email, however this option will be passed into the hexo util for gravatar only by providing the email address.
https://github.com/probberechts/hexo-theme-cactus/blob/110370ac0fb50a336e662d073cebedb69e184feb/layout/_partial/header.ejs#L5
I wonder whether you can add support for passing in the hash value of email, which is the gravatar id.
Thanks.

**Comment by CSY54** [comment]
Just curious, can this proposal be supported? If so, I can implement this.

**Comment by probberechts** [comment]
Yes. This is a good suggestion. A pull request would be very welcome.
