### ISSUE TITLE
About Search (wrong URL)

### ISSUE THREAD

**Issue by ColderCoder** [probberechts/hexo-theme-cactus#247]
I'm using `hexo: 5.2.0` with `hexo-generator-search@2.4.1`.  
The search page works fine and I can see results as I type.  
But the search function will auto append `search/` after the root path.  
(e.g.) It should be `localhost:4000/post/something/` while it returns `localhost:4000/search/post/something/`

**Comment by probberechts** [comment]
This is a bug in hexo-generator-search. See https://github.com/wzpan/hexo-generator-search/issues/66.

**Comment by sirlh** [comment]
[A solution](https://github.com/Nothing-lin/hexo-theme-coolshell/commit/a8df031d3ee73d812c0416633b72b120f156ee7f)

**Comment by ATommyGirl** [comment]
I replace the `search.js` by this [Ocean-search.js](https://github.com/zhwangart/hexo-theme-ocean/blob/develop/source/js/search.js). It worked.

**Comment by ColderCoder** [comment]
> 
> 
> [A solution](https://github.com/Nothing-lin/hexo-theme-coolshell/commit/a8df031d3ee73d812c0416633b72b120f156ee7f)

Than you! It does work for me. 
@probberechts  Maybe we should apply this simple fix?

**Comment by probberechts** [comment]
@sirlh's solution only works if your website is hosted at the root (see also #287). While this fixes the problem for some people, it would break the search functionality for others. This really has to be fixed in hexo-generator-search.

**Comment by probberechts** [comment]
This is fixed in hexo-generator-search@2.4.3 :tada:
