### ISSUE TITLE
How to add the introdution paragraph under the navbar

### ISSUE THREAD

**Issue by PiktCai** [probberechts/hexo-theme-cactus#268]
I see the paragraph

`Hi, I’m a theme for the Hexo blogging framework. I’m particularly great for a personal web page with a simple blog. In this paragraph, you can provide some information about yourself. Below, you’re most recent or highlighted writings and projects are listed.`

in demo, but how can do this? Please help

**Comment by xuyifangreeneyes** [comment]
Hi, i have the same question. @PiktCai do u find a way to do that? thx~

**Comment by PiktCai** [comment]
> Hi, i have the same question. @PiktCai do u find a way to do that? thx~

Just edit the description in the _config.yml of the whole site (not the theme).

**Comment by xuyifangreeneyes** [comment]
Thanks a lot!

**Comment by Kemuda** [comment]
Hi Guys, I have a problem of the description in the main config document does not load on the page. I checked the index.ejs and it's in the right way.  I'm using zh-cn as the language. not sure if this leads to the problem.

**Comment by Kemuda** [comment]
I tried a lot of things(including rewriting the ejs file). But what eventually worked was changing the site language to English and then back... NVM, it is solved  ;P
