### ISSUE TITLE
Bottom Lines of Search Results are Cut in Half

### ISSUE THREAD

**Issue by UM-Li** [probberechts/hexo-theme-cactus#272]
I tested on both desktop and mobile versions and got the same result.

![Screenshot_20210127_221920](https://user-images.githubusercontent.com/6215580/106090017-c47de500-60ee-11eb-96ad-de0db6db7ce1.png)

**Comment by probberechts** [comment]
It looks fine on my side in the demo (see https://probberechts.github.io/hexo-theme-cactus/cactus-dark/public/search/). Which browser and version do you use?

**Comment by UM-Li** [comment]
Hi, I'm using Firefox 85.0. From what I can see this bug is also present in the Cactus Dark demo.

The search functionality presents results in two different ways when the paragraph is too long:
- Sometimes it truncates the paragraph and adds `...` at the end, in which case the bottom line is displayed correctly;
- Sometimes the truncation does not happen, and the bottom line will be cut in half.

As far as I have tested this bug only happens when there is no truncation.

![Screenshot_20210130_121919](https://user-images.githubusercontent.com/6215580/106364580-ab935080-62f5-11eb-9c88-3597c110b8a1.png)

**Comment by foxB612** [comment]
Confirm the same bug and I think it's related to `substr()` in `search.js`.
![image](https://user-images.githubusercontent.com/58619636/115342623-1fe6dd00-a1dd-11eb-9c06-eed4bcaf3918.png)
It seems that we should use `substring()` here?
