### ISSUE TITLE
First level heading not displayed as link

### ISSUE THREAD

**Issue by ApplePie420** [probberechts/hexo-theme-cactus#274]
When you have the side menu open, you can see quick links to the different sections of the page. This system is great, but for some reason, it does not display link to level 1 headings:

![image](https://user-images.githubusercontent.com/21370314/106840527-a2610580-66a0-11eb-99e0-f4ab6cefc5fc.png)
This is what I have in the .md file

![image](https://user-images.githubusercontent.com/21370314/106840562-b3aa1200-66a0-11eb-8196-34e9652b285a.png)
And here is the page snapshot. The heading displays properly, but link on the side menu is not present.

**Comment by probberechts** [comment]
See #118
