### ISSUE TITLE
How to display envelope icon for link to email address at index page?

### ISSUE THREAD

**Issue by bunnyxt** [probberechts/hexo-theme-cactus#280]
Sorry to interrupt you guys! I'm new to hexo and have 2 problems related to this theme. Hope someone could help me.

I notice that the demo displays an envelope on the index page for link to email address, like this

<img width="769" alt="Screen Shot 2021-03-19 at 23 08 23" src="https://user-images.githubusercontent.com/32478279/111801670-1cbfaf00-8908-11eb-9f69-276efebf5529.png">

I try to replicate this by set in _config.yml

```
theme_config:
  social_links:
    envelope: mailto:example@outlook.com
```

However, it cannot display correctly, like this

<img width="743" alt="Screen Shot 2021-03-19 at 23 07 08" src="https://user-images.githubusercontent.com/32478279/111801864-509ad480-8908-11eb-8a32-c8d2b1246028.png">

How should I set to display that envelope icon? By the way, I want to add some description above 'Find me on...' line, just like the demo shows 'Hi, I’m a theme for the Hexo blogging framework...'. What should I do? Thanks a lot!

**Comment by mgrddsj** [comment]
Take a look at the comments in the theme config file that comes with the theme, it says "mail" is an exception.

![image](https://user-images.githubusercontent.com/36990144/114871350-c91f8300-9e2b-11eb-82c4-7a69fcbc94ea.png)

So, you should put `mail: mailto: example@outlook.com` under `social_links`.

For your other question, the text above "find me on ..." is the `description` in the hexo config file (not the theme config).
![image](https://user-images.githubusercontent.com/36990144/114871867-51058d00-9e2c-11eb-9d24-f493e839aadd.png)
![image](https://user-images.githubusercontent.com/36990144/114871901-5c58b880-9e2c-11eb-8d5f-d0c74002a28e.png)


Hope this helps.
