### ISSUE TITLE
which files do i need to modify to change layout style?

### ISSUE THREAD

**Issue by clubfocus** [probberechts/hexo-theme-cactus#281]
hi guys, I want to change layout style, like  as follows.

![layout](https://user-images.githubusercontent.com/80865099/111890157-d2325580-8a21-11eb-9e05-6b0b80a5fbab.jpg)

I think I need to change body/content/header/footer, but I don't know which one, can anyone kind help?

**Comment by probberechts** [comment]
Sorry, but it is not clear at all to me what you would like to achieve. You can find all styles in `source/css`.
