### ISSUE TITLE
Question about delete all the blogs

### ISSUE THREAD

**Issue by xw547** [probberechts/hexo-theme-cactus#282]
Hi,

First off, thank you so much for the nice theme! It looks perfect.

However, I intended to make this theme into a personal website without any blog. Is it possible for me to do so? That is, can I delete the writing entry and all the blogs of my website and still make it accessible?

Thank you in advance:)

**Comment by probberechts** [comment]
Sure, you can [remove the link to the blog archive](https://github.com/probberechts/hexo-theme-cactus/blob/7d4104173d7253f95905f83ed1a24bfd0062baf3/_config.yml#L19) from the navigation menu and adapt the home page layout (remove [this part](https://github.com/probberechts/hexo-theme-cactus/blob/7d4104173d7253f95905f83ed1a24bfd0062baf3/layout/index.ejs#L34)).
