### ISSUE TITLE
theme_icon_font awesome icon

### ISSUE THREAD

**Issue by xiefei-ok** [probberechts/hexo-theme-cactus#285]
![image](https://user-images.githubusercontent.com/56799427/115073761-5a295380-9f2b-11eb-9b3d-4e0ad4b8ebf3.png)

What should I do if the application icon I want is not found in this lib(font awesome icon)?

**Comment by probberechts** [comment]
You'll have to add the icon to your assets folder and add a custom link in [the index layout](https://github.com/probberechts/hexo-theme-cactus/blob/86f60eaa4b451bc359b27855ce98a903ab78aa6a/layout/index.ejs#L7).
