### ISSUE TITLE
TOC overlaps in Chrome

### ISSUE THREAD

**Issue by Konfido** [probberechts/hexo-theme-cactus#289]
It seems the menu icon and TOC overlaps in Chrome, but it words well in Safari.

<img src="https://user-images.githubusercontent.com/25447610/118863633-b956fb00-b911-11eb-8e59-ae8e27c72525.png" height=300>
<img src="https://user-images.githubusercontent.com/25447610/118863495-8b71b680-b911-11eb-9df0-3cabcf1b8281.png" height=300>

**Comment by probberechts** [comment]
Do you experience the same issue [in the demo](https://probberechts.github.io/hexo-theme-cactus/cactus-dark/public/2016/11/14/hello-world/)? If not, this is probably a bug in the most recent commit (#286).

**Comment by Konfido** [comment]
> Do you experience the same issue [in the demo](https://probberechts.github.io/hexo-theme-cactus/cactus-dark/public/2016/11/14/hello-world/)? If not, this is probably a bug in the most recent commit (#286).

I just found out it worked well in Incognito Mode of Chrome, and further identified this problem is caused by a Chrome extension "AdGuard". But it's a little strange that the extension shows it didn't block any element.
