### ISSUE TITLE
Font Awesome icons in page text

### ISSUE THREAD

**Issue by manestay** [probberechts/hexo-theme-cactus#298]
(sorry if this is the wrong place to ask this)

Is there a way to have the Font Awesome icons in the page text? I see that `themes\cactus\layout\index.ejs` has some code for displaying the links. However, I created a custom homepage by making file `source/index.md`, so I don't have the icons anymore. Ideally I would like the icons in the .md file.

**Comment by probberechts** [comment]
The Font Awesome font is included in the theme and you can include HTML in markdown files. Hence, you can add icons as instructed here: https://fontawesome.com/docs/web/add-icons/how-to

For example:
```md
# Page title

Here is an icon: <i class="fa fa-tint" aria-hidden="true"></i>
```

**Comment by manestay** [comment]
It works! Thanks so much for the fast response. Total web design noob here :)
