### ISSUE TITLE
 Does google analytics on Hexo&Cactus require a "UA-" ID? Or it is fine with a "G-" ID?

### ISSUE THREAD

**Issue by Kemuda** [probberechts/hexo-theme-cactus#299]
GA4 updates brought this problem. I used the G ID in the configure file but the data did not go through to Google Analytics. 

Can anyone help?

**Comment by probberechts** [comment]
On our side, the change to GA4 does not require any action. The gtag.js snippets for a Universal Analytics property and for a Google Analytics 4 property are fundamentally the same ([source](https://support.google.com/analytics/answer/9310895?hl=en#zippy=%2Cin-this-article)). Moreover, the UA property is supported until July 1, 2023 ([source](https://support.google.com/analytics/answer/10089681?hl=en)). 

I'll close this as I do not think this is an issue related to hexo-theme-cactus.
