### ISSUE TITLE
Cannot GET /projects_url 

### ISSUE THREAD

**Issue by KhazanGu** [probberechts/hexo-theme-cactus#301]
I changed the value of projects in the theme's _config.yml. After that, I cleaned and generated a new blog, I got a "Cannot GET /projects_url " warning in the browser after I click the projects item. Thanks for your help.

I changed the value of projects to http://github.com/probberechtss.
<img width="380" alt="Screen Shot 2022-02-17 at 10 07 00" src="https://user-images.githubusercontent.com/14102044/154390787-f0007cd8-2445-4181-b201-1e97c268adcf.png">

It doesn't work.
<img width="401" alt="Screen Shot 2022-02-17 at 10 05 26" src="https://user-images.githubusercontent.com/14102044/154390660-45dbe7aa-bc84-4d5d-afcb-6e952cfe42fd.png">

**Comment by hamzakat** [comment]
Same thing with me. It must work for you by adding the URL instead of using the variable "projects_url".
