### ISSUE TITLE
Image Sizing

### ISSUE THREAD

**Issue by nataliepjlin** [probberechts/hexo-theme-cactus#306]
hello! i added [this package](https://www.npmjs.com/package/hexo-image-link-with-display-size) to my hexo site. after installing, when using `![image](./about/images/profile.jpg)`, it works fine. but it doesn't work when using `![image](./about/images/profile.jpg =36x36)`. is there any ways to fix this, or is there any other tools that can set images' sizes?

**Comment by probberechts** [comment]
You can use one of Hexo's [tag plugins](https://hexo.io/docs/tag-plugins#Embed-image)
```
{% img [class names] /path/to/image [width] [height] '"title text" "alt text"' %}
```
or raw HTML
```html
<img src="/path/to/image" alt="alt text" style="width:200px;"/>
```

**Comment by nataliepjlin** [comment]
@probberechts I tried both `<img src="/images/profile.jpg" width="40" height="40">` and `{% asset_img profile.jpg 30 30 %}` but none of these work. Do I need to create a new path or move the `images` folder to another places?? 
my repo: https://github.com/nataliepjlin/heeexo
thanks a lot!!!

**Comment by probberechts** [comment]
I do not know why the HTML tag does not work, but `asset_img` has to be used in conjunction with [post_asset_folder](https://hexo.io/docs/asset-folders). Try with the normal `img` tag instead.

**Comment by nataliepjlin** [comment]
@probberechts I'm not sure what happened but now it says `Markdown Image Path does not exists!`, also even `![image](/source/images/profile.jpg)` can't display
