### ISSUE TITLE
The "**原子性**" markdown bold  singal does not work

### ISSUE THREAD

**Issue by 535704264** [probberechts/hexo-theme-cactus#309]
<img width="767" alt="image" src="https://user-images.githubusercontent.com/31807632/160427032-0218aec8-0b55-4b90-a3ca-c3025569d00f.png">

**Comment by probberechts** [comment]
Did you manage to resolve this? It does seem to work in the demo. See https://probberechts.github.io/hexo-theme-cactus/cactus-white/public/2016/11/01/An-overview-of-all-Markdown-elements/#Emphasis
