### ISSUE TITLE
Is it possible to add menu children to the navigation bar ? 

### ISSUE THREAD

**Issue by SofianeHamlaoui** [probberechts/hexo-theme-cactus#319]
I’ve been using Cactus theme for a moment for my blog.

but lately I wanted to add articles in more languages, where I needed to add a menu to the navigation bar for the multiple languages.

is it possible to add children to the menus ? 

Like in the default configuration of hexo  ? 

thanks in advance.

**Comment by probberechts** [comment]
No, there is no multi-language support in this theme. If you want it, you'll have to implement it yourself.
