### ISSUE TITLE
Unable to highligh Solidity code

### ISSUE THREAD

**Issue by theNvN** [probberechts/hexo-theme-cactus#322]
With current config Solidity language code blocks are not highlighted and I'm unable to figure out how to enable it. Can you pls show me how to go about adding the support?

**Comment by probberechts** [comment]
Hexo has two built-in syntax highlight libraries, [highlight.js](https://github.com/highlightjs/highlight.js) and [prismjs](https://github.com/PrismJS/prism). It seems that only prismjs supports the Solidiy language, but this theme is configured to use hishlight.js (we use Hexo's default settings). In the [Hexo docs](https://hexo.io/docs/syntax-highlight.html) you can find instructions on how you can enable prismjs instead.
