### ISSUE TITLE
color scheme doesn't work

### ISSUE THREAD

**Issue by fighting41love** [probberechts/hexo-theme-cactus#332]
> # Set the color scheme.
> # Available color schemes are 'dark', 'light', 'classic' and 'white'.
> # Alternatively, add your own custom color scheme to source/css/_colors.
> colorscheme: white #dark
> 

I set the color scheme as white, and I confirm by http://localhost:4000.
However, when I depoy the files to github, it is dark theme, as shown: http://fighting41love.github.io/

could someone figure out the problems?

Thanks!

**Comment by probberechts** [comment]
Looking at your website, it looks like you've managed to resolve it. It would be great if you could share your solution to help others.

**Comment by JerryYan24** [comment]
I have the same problem too, how do you solve it in the end.

**Comment by JerryYan24** [comment]
hexo c != hexo clean

**Comment by ShinWhy** [comment]
> Looking at your website, it looks like you've managed to resolve it. It would be great if you could share your solution to help others.

I met the same problem. How to solve it? Thank you very much! Here is my website: https://shinwhy.github.io/

**Comment by ShinWhy** [comment]
> hexo c != hexo c
I saw you have solved the problem. Could you please share what you did? Thank you very much!

**Comment by JerryYan24** [comment]
Hi, my friend. Before you use hexo g, use hexo clean first, then hexo g, hexo d. Do notice that hexo clean is not hexo c. Good luck!

Jerry Yan
________________________________
