### ISSUE TITLE
Page title exception of archives page.

### ISSUE THREAD

**Issue by ghost** [probberechts/hexo-theme-cactus#344]
After I set the language to zh CN, the page titles of other pages are normally displayed as zh CN, but the header text of the built-in archives page is abnormal and displayed as Arabic.      منشورات

**Comment by probberechts** [comment]
That's odd. Did you try running `hexo clean` already?

**Comment by 6ams5Y2g5Lic** [comment]
> That's odd. Did you try running `hexo clean` already?

Yes, I tried many methods, including hexo clean, and the results were the same. The others were displayed normally, but the tag page title of the archive page was displayed abnormally

**Comment by probberechts** [comment]
Just to be clear, you are refering to the `<title>` tag, right?

Does it change to English if you set the language in `_config.yml` to 

```yaml
language:
- zh-CN
- en
```

**Comment by 6ams5Y2g5Lic** [comment]
> 澄清一下，你指的是`<title>`标签，对吗？
> 
> `_config.yml`如果您将语言设置为，它会更改为英语吗
> 
> ```yaml
> language:
> - zh-CN
> - en
> ```

If it is changed to en, the title is writing, and if it is changed to zh CN, the title is منشورات

**Comment by 6ams5Y2g5Lic** [comment]
![IMG20230106005446.jpg](https://user-images.githubusercontent.com/122037574/210836973-202ea958-b7e8-4854-862b-22c6833e4de1.jpg)

**Comment by probberechts** [comment]
This is the relevant code that sets the title of the archive page: https://github.com/probberechts/hexo-theme-cactus/blob/f44dcaf1404bef7645fc92d7c06b2bfbef06c45a/scripts/page_title.js#L11

The `nav.articles` variable is replaced with https://github.com/probberechts/hexo-theme-cactus/blob/f44dcaf1404bef7645fc92d7c06b2bfbef06c45a/languages/zh-CN.yml#L4

I do not see what would be wrong here. Hence, I am afraid I cannot solve it. If you manage to debug it, let me know.

**Comment by 6ams5Y2g5Lic** [comment]
> This is the relevant code that sets the title of the archive page:
> 
> https://github.com/probberechts/hexo-theme-cactus/blob/f44dcaf1404bef7645fc92d7c06b2bfbef06c45a/scripts/page_title.js#L11
> 
> The `nav.articles` variable is replaced with
> 
> https://github.com/probberechts/hexo-theme-cactus/blob/f44dcaf1404bef7645fc92d7c06b2bfbef06c45a/languages/zh-CN.yml#L4
> 
> I do not see what would be wrong here. Hence, I am afraid I cannot solve it. If you manage to debug it, let me know.

If the problem has been solved, thank you for your patient reply.

**Comment by probberechts** [comment]
What was the solution?

**Comment by 6ams5Y2g5Lic** [comment]
> 解决方案是什么？

/languages/zh-CN.yml       as a result of articles: 归档 is modified to article: 归档 by me
