### ISSUE TITLE
Add a switch to close <section id="about"> adn <section id="projects">

### ISSUE THREAD

**Issue by ghost** [probberechts/hexo-theme-cactus#347]
/layout/index.ejs Line 1 <section id="about"> and Line 63 <section id="projects">

Is this content mandatory? If so, I hope the author can add a switch, because I just want to write. For me, the main page contains articles. Because of the different needs of each person, you want to add a switch to control whether this content is displayed.
I didn't find the switch, so I deleted/layout/index.ejs Line 1<section id="about">and other contents.

**Comment by probberechts** [comment]
I do not plan to implement this. It is impossible to add a configurable option for every possible user preference. If you want something custom, just edit the HTML as you did.
