### ISSUE TITLE
TOC entry for H1 headings are set to display: none

### ISSUE THREAD

**Issue by cbreezier** [probberechts/hexo-theme-cactus#349]
This looks very intentional, because the css is specifically configured to hide the link: https://github.com/probberechts/hexo-theme-cactus/blob/master/source/css/_partial/post/actions_desktop.styl#L135

```
    .toc-level-1 > .toc-link
      display: none
```

My question is: why is it hidden? It looks pretty weird in the TOC because it ends up only rendering a bullet point for the `::marker`. Could this have been a genuine mistake that snuck into the css? Or is there a good reason for hiding it?

Thanks for your time!

**Comment by probberechts** [comment]
Yes, this is intentional. The blog post title is the H1 header. I do not want to include it in the TOC, because that would use up a level and there is already a button to go back to the top of the page. You should not include any other H1 headings in your blog post.

**Comment by cbreezier** [comment]
Thanks for clarifying @probberechts. I guess you're right - semantically, there should be just one H1 heading.
