### ISSUE TITLE
Integrate cactus-light and cactus-white

### ISSUE THREAD

**Issue by probberechts** [probberechts/hexo-theme-cactus#74]
I've recently found out about the [Cactus Light](https://github.com/gabithume/cactus-light) (by @GabiThume) and [Cactus White](https://github.com/sergodeeva/cactus-white) (by @sergodeeva) themes. I think they look great and would like to integrate them in the Cactus Dark theme (and maybe drop the 'Dark' in the name?). This would focus the development again on a single version and would make it easier for the users to alter the colorscheme.

Cactus Dark, Cactus White and Cactus Light are mainly variations on the colorscheme, so it would be easy to merge them by creating a separate `colors.styl` file for each colorscheme and adding a `customize.colorscheme` hexo config variable.

Do you agree @sergodeeva and @GabiThume?

**Comment by GabiThume** [comment]
Sure @probberechts! I think it is a great idea, let me know if there is anything I can do.

**Comment by sergodeeva** [comment]
Good idea @probberechts :)
