### ISSUE TITLE
Alerts, fancybox, categories

### ISSUE THREAD

**Issue by h0ek** [probberechts/hexo-theme-cactus#78]
Hi!

Great theme. Is it possible to implement alerts boxes like on this hexo theme?
https://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2014/10/29/Tags-plugins-showcase/#Alert

and fancybox for image preview?
https://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2014/10/29/Tags-plugins-showcase/#Image

I just started with hexo and need to learn a lot. Thanks in advance!

**Comment by probberechts** [comment]
> Is it possible to implement alerts boxes like on this hexo theme?

I will not implement this. I try to keep the theme basic and only support the [tag elements](https://hexo.io/docs/tag-plugins.html) that are defined by hexo.

> and fancybox for image preview?

Again, same reason. But there is a plugin for lightbox  which has similar functionality (see #70).

**Comment by h0ek** [comment]
Perfect, this make sense. Thanks.
