### ISSUE TITLE
Remove 2px border-top from style.

### ISSUE THREAD

**Issue by franccesco** [probberechts/hexo-theme-cactus#79]
Is there any reason to keep this line? It adds a grey line at the top of the page. I don't know if it serves a purpose for the light and grey theme but it doesn't look good for the dark theme. 

https://github.com/probberechts/hexo-theme-cactus/blob/43df0ccb23f3fad5eef517db1a40e41cbab3b912/source/css/style.styl#L15

### After
![image](https://user-images.githubusercontent.com/6962824/37856413-f83edfa8-2eb9-11e8-863c-3a015563aaf9.png)

### Before removing border-top
![image](https://user-images.githubusercontent.com/6962824/37856424-04a2df1a-2eba-11e8-9778-3754aa365d1f.png)

**Comment by probberechts** [comment]
It's part of the design. I like how it adds a subtle accent and clearly marks the top of the page. I will not remove it, but feel free to do so in a fork if you don't like it.
