### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by iota9star** [probberechts/hexo-theme-cactus#81]
![uc 20180325222707](https://user-images.githubusercontent.com/21272154/37876228-0a662b82-307c-11e8-84e2-e2c2737eb8bc.png)

i don't konw what happen?

**Comment by iota9star** [comment]
![uc 20180326090517](https://user-images.githubusercontent.com/21272154/37882359-3ac7e474-30d5-11e8-8005-6bd84758d370.png)
![_config yml](https://user-images.githubusercontent.com/21272154/37882363-3f989b88-30d5-11e8-832e-163d1a90defc.png)
![_config yml](https://user-images.githubusercontent.com/21272154/37882375-62a2e458-30d5-11e8-959d-57a6fbb91903.png)

**Comment by iota9star** [comment]
i disable the RSS feed. it's ok. thanks
![uc 20180326091251](https://user-images.githubusercontent.com/21272154/37882451-02a372ec-30d6-11e8-842e-0e2333f963ac.png)

**Comment by probberechts** [comment]
If you set `rss: true`, you have to install the [hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed) plugin.
