### ISSUE TITLE
Renders perfect on localhost but the pages crash on GitHub.io

### ISSUE THREAD

**Issue by naco-siren** [probberechts/hexo-theme-cactus#83]
<img width="569" alt="screen shot 2018-03-25 at 10 29 55 pm" src="https://user-images.githubusercontent.com/8222638/37888405-355e6e30-307c-11e8-9958-7aaf965e85e5.png">

**Comment by probberechts** [comment]
Is this <https://naco-siren.github.io>? Because that page renders perfectly in my browser.
Otherwise, could you post the `_config.yml` file and give me the Github pages URL?

**Comment by naco-siren** [comment]
@probberechts Wow now I found it correct, too.
No idea what happened...perhaps it's GitHub's glitches?
Anyway no problem now, thanks!
