### ISSUE TITLE
possibility of a port for Hugo?

### ISSUE THREAD

**Issue by Deckon** [probberechts/hexo-theme-cactus#88]
Well, just that. regards

**Comment by probberechts** [comment]
I don't have the time/motivation to do it myself on the short term. However, the license (MIT) is very open, so feel free to implement it yourself. I would be happy to contribute.

I will leave this issue open for some time. Maybe others are interested to contribute?

**Comment by ysicing** [comment]
@Deckon  I did it. But it might not suit you very well.You can refer to it. Hugo theme is very flexible.
[cactus-hugo-theme](https://github.com/ysicing/cactus-hugo-theme) [demo](https://blog.spanda.io/)

thank @probberechts .
