### ISSUE TITLE
what should I do if I want to create new page tags.

### ISSUE THREAD

**Issue by otwayz** [probberechts/hexo-theme-cactus#92]
I run the command

hexo new page tags

But nothing happens in the nav  tags. ( already add  nav : tags: /tags/)

**Comment by probberechts** [comment]
Did you check the following:
1. Did `hexo new page tags` create a file `source/tags/index.md`?
2. What is the value of the `href` attribute in the generated html source?
3. Did `hexo generate` create a file in `public/tags/`

**Comment by MurasakiSeiFu** [comment]
blog/source/categories/index.md
title: categories
date: 2014-12-22 12:39:04
type: "categories"
---

hexo-theme-cactus/_config.yml
nav:
  home: /
  Me : /about/
  categories: /categories/

One of the posts
---
title: test1
date: 2018-04-16 17:40:03
categories: Hexo
---


I run the command
hexo clean 
hexo g 
hexo server
When I click on the category in the page
It shows nothing -.-
![image](https://user-images.githubusercontent.com/27035547/38807587-b3fe5694-41af-11e8-9417-f2b68fc33779.png)

but the page has been generated...
![image](https://user-images.githubusercontent.com/27035547/38807520-6d336736-41af-11e8-94d3-2e65361d5665.png)

I haven't solved it yet. I hope you can help me. I'm so grateful!
If I bother you, I'm sorry....
Best wishes！

**Comment by probberechts** [comment]
Oh, I think I understand you. This theme does not have a layout for tags, nor categories.
See my answer in #35 for a solution.
