### ISSUE TITLE
What are the rules of contribute?

### ISSUE THREAD

**Issue by mehrad77** [probberechts/hexo-theme-cactus#93]
Hi again.

I'm adding lots of thing on this theme for my own blog and I was thinking that is it ok to make pull requests for some of them?
Things like integrations with _featured images_ or [_RTL support_](https://github.com/probberechts/hexo-theme-cactus/pull/89 ) or _footnotes_ or _emojis_ and so on.

So what's the rules? You want to make this theme simple by not adding the extra features or is it ok to add some?

**Comment by mehrad77** [comment]
Oh! I didn't know about `photos:`. Shouldn't be mentioned in `README.md`? 
And thank you for declaring your recommendations.

**Comment by probberechts** [comment]
`photos` is actually a tag supported by [core Hexo](https://github.com/hexojs/hexo/blob/92827129f37600d5dd2939d28ef46f66db5e23dd/lib/models/post.js#L39), so I think it should rather be documented there.
