### ISSUE TITLE
projects.json doesn't render markdown?

### ISSUE THREAD

**Issue by finetype** [probberechts/hexo-theme-cactus#95]
Nor does it seem to allow html. No way to get hyperlinked text in the descriptions at first glance here... Thoughts?

**Comment by kezhenxu94** [comment]
I don't know whether this is intentionally designed by @probberechts or not, I just create a PR to fix this.

**Comment by finetype** [comment]
Nice. Looks like it was a single character typo, from your pull request, no? Good catch.

**Comment by finetype** [comment]
Hm. I tried copying that commit to my local repo, but it still doesn't render markdown for the project descriptions.
