### ISSUE TITLE
Search includes HTML/Markdown

### ISSUE THREAD

**Issue by egordorichev** [probberechts/hexo-theme-cactus#98]
![screenshot from 2018-04-27 21-38-08](https://user-images.githubusercontent.com/7851390/39379224-4ab9a082-4a63-11e8-8cea-76033e3ed090.png)

Is there anyway to fix that? :/

**Comment by probberechts** [comment]
I will need more information to understand your problem. Is the `a { display: none; }` part of the source of the post (e.g., a code block)? 
Could you share the markdown version of that post? Or provide a link to your blog, if it is already online?

**Comment by egordorichev** [comment]
```
---
title: Curse of the Arrow
date: 2018-04-23 14:49:25
tags: cota
---

<style>
.meta {
  display: none;
}
</style>

**Curse of the Arrow** is a puzzle platformer, where the only weapon is a bow and a **_single arrow_**. Doesn't sound like a lot, huh? Well, not only that but **it's been cursed, so now it spreads corruption around itself**.

Explore areas, solve puzzles, and fight against _your curse!_

Use your arrows as platforms, fight against enemies, toggle switches, and push boxes, and die (over and over)!

**Comes later this summer on Steam, till then, stay tuned for more updates [on our twitter!](https://twitter.com/rexcellentgames)**
```

Sure, here it is/ But that's not the only tag it shows if I'm right.
