### ISSUE TITLE
Some suggestions to optimize the theme

### ISSUE THREAD

**Issue by Kakise** [probberechts/hexo-theme-cactus#99]
Hello, I've got some suggestions that I implemented on my blog with no problems (https://github.com/Kakise/Blog/tree/master/themes/cactus).

  - Change font display method to: [font-display: swap ](https://developer.mozilla.org/en-US/docs/Web/CSS/%40font-face/font-display)
  - Let the user load Disqus manually and removes the script from the index as the comment count isn't shown anyway. It avoids having useless js scripts loaded, if a user wants to leave a comment, he'll press the "Load comments" button. Also, it avoids having external trackers for no reasons: https://github.com/Kakise/Blog/blob/master/themes/cactus/layout/_partial/comments.ejs https://github.com/Kakise/Blog/blob/master/themes/cactus/layout/_partial/scripts.ejs

I added the necessary translations in French and English. Check out here: https://github.com/Kakise/Blog/tree/master/themes/cactus/languages

What do you think about those improvements?

**Comment by probberechts** [comment]
Thanks for your suggestions and I'm sorry for the late reply. This is what I think:
- `font-display: swap` is a good suggestion. I will incorporate this.
- If you enable comments, this probably means that you want your readers to actually make comments. Hiding the comment section is then an additional barrier and decreases the likelihood that someone leaves a comment behind. Therefore, I don't think that your second suggestion is a good idea. The comment section is already loaded asynchronously, so it doesn't affect the loading time of the main content.
